version: '3.9'

services:
  backend:
    build: ./backend
    platform: linux/x86_64
    container_name: todolist-backend
    ports: 
     - 3001:3001
    restart: 'always'
    command: npm run dev
    volumes:
      - './backend/src:/app/src'
    depends_on:
      mysql_database:
        condition: service_healthy
    environment:
      - PORT=${PORT}
      - DB_USER=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - DB_HOST=${DATABASE_HOST}
      - DB_NAME=${DATABASE_NAME}
      - DB_PORT=${DATABASE_PORT}
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
  mysql_database:
    image: mysql:8.0.21
    container_name: mysql_database
    ports: 
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE 


